
tomcat:
  apr: true

# eureka
eureka:
  client:
    enabled: false
    healthcheck: false
      

redis:
  database: 0
  timeout: 1000
  port: 6379
  host: redis_single
  pool:
    max-active: 100
    max-idle: 20
    min-idle: 5
    max-wait: 1000
  
micro:
  services:
    microee-traditex-inbox-app:
      listOfServers: http://127.0.0.1:28081

# redis topics
topic:
  traditex:
    httplog.listener.message: __traditex.message.httplog.listener_${spring.profiles.active}
    
