server:
  port: 28082
  tomcat:
    basedir: ${java.io.tmpdir}/@project.name@_${server.port}
    
spring:
  profiles:
    active: local
  application:
    name: microee-traditex-liquid-app


# redis topics
topic:
  traditex:
    pricing.message: __traditex.message.pricing_${spring.profiles.active}
    orderbook.message: __traditex.message.orderbook_${spring.profiles.active}
    diskorders.message: __traditex.message.diskorders_${spring.profiles.active}
    revokeorder.count.message: __traditex.message.revokeorder.count_${spring.profiles.active}
    account.balance.message: __traditex.message.account.balance_${spring.profiles.active}
    httpnetwork.message: __traditex.message.httpnetwork_${spring.profiles.active}
    httplog.listener.message: __traditex.message.httplog.listener_${spring.profiles.active}

