
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d
version: '2.4'
networks:
    br0:
      external: true

services:
  liquidity.inbox:
    container_name: liquidity.inbox
    image: chunhui2001/alpine:3.9.tomcat8.5
    hostname: liquidity.inbox
    mem_limit: 300m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 18081:18081
    entrypoint: ["java", "-Djava.library.path=/usr/local/tomcat/native-jni-lib", "-jar", "/root/app/app.jar"]
    volumes:
      - ./target/microee-traditex-inbox-app-1.0-SNAPSHOT.jar:/root/app/app.jar:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.114
  microee.traditex.liquid:
    container_name: microee.traditex.liquid
    image: chunhui2001/alpine:3.8.tomcat-8.5
    hostname: microee.traditex.liquid
    mem_limit: 300m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 18081:18081
    entrypoint: ["java", "-Djava.library.path=/usr/local/tomcat/native-jni-lib", "-jar", "/root/app/app.jar"]
    volumes:
      - ./target/microee-traditex-liquid-app-1.0-SNAPSHOT.jar:/root/app/app.jar:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.115
  microee.traditex.hello:
    container_name: microee.traditex.hello
    image: chunhui2001/alpine:3.8.tomcat-8.5
    hostname: microee.traditex.hello
    mem_limit: 300m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 18084:18084
    entrypoint: ["java", "-Djava.library.path=/usr/local/tomcat/native-jni-lib", "-jar", "/root/app/app.jar"]
    volumes:
      - ./target/microee-traditex-hello-app-1.0-SNAPSHOT.jar:/root/app/app.jar:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.117
  microee.traditex.web:
    container_name: microee.traditex.web
    image: chunhui2001/alpine:3.8.tomcat-8.5
    hostname: microee.traditex.web
    mem_limit: 300m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 18083:18083
    entrypoint: ["java", "-Djava.library.path=/usr/local/tomcat/native-jni-lib", "-jar", "/root/app/app.jar"]
    volumes:
      - ./target/microee-traditex-web-app-1.0-SNAPSHOT.jar:/root/app/app.jar:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.116



