
server:
  port: 18083
  tomcat:
    basedir: ${java.io.tmpdir}/@project.name@_${server.port}
    
spring:
  profiles:
    active: local
  application:
    name: microee-traditex-web-app
    
redis:
  database: 0
  timeout: 1000
  port: 6379
  host: redis_single_auth
  pool:
    max-active: 100
    max-idle: 20
    min-idle: 5
    max-wait: 1000

# redis topics
topic:
  traditex:
    httplog.listener.message: __traditex.message.httplog.listener_${spring.profiles.active}
