
server:
  port: 18084
  tomcat:
    basedir: ${java.io.tmpdir}/@project.name@_${server.port}
    
spring:
  profiles:
    active: local
  application:
    name: microee-traditex-hello-app
    
redis:
  database: 0
  timeout: 1000
  port: 6379
  host: redis_single_auth
  pool:
    max-active: 100
    max-idle: 20
    min-idle: 5
    max-wait: 1000
